CREATE TABLE SubmittedBids(
	id int NOT NULL AUTO_INCREMENT,
	bidRequestID int COMMENT 'hidden property',
	cbrID int COMMENT 'hidden property',
	reservationID int,
	propertyLevel varchar(20) COMMENT 'Property Level: ABC or Hotel.',
	propertyName varchar(255),
	propertyAddress varchar(255),
	city varchar(255),
	state varchar(2) COMMENT 'State can only be two letters',
	zip int,
	apxDistance varchar(255),
	unitSize varchar(255) COMMENT 'Unit type (studio 1 bedroom etc...)',
	aptSize int,
	rateUOM varchar(255) COMMENT 'Rate Unit of Measure (daily nightly monthly)',
	rateAmount decimal COMMENT 'Actual dollar rate amount',
	taxRate varchar(255),
	otherFees varchar(255),
	dateAvailable DATE,
	minLeaseTerm varchar(255),
	longTermDiscount varchar(255),
	internet varchar(255),
	phone varchar(255),
	cable varchar(255),
	laundry varchar(255),
	maid varchar(255),
	parking varchar(255),
	parkingFee varchar(255) COMMENT 'Is it included or not (yes or no)',
	parkingFeeAmt decimal COMMENT 'actual parking fee dollar amount',
	petPolicy text COMMENT 'I guess it is a comment box so there is a text field here',
	petFee decimal COMMENT 'dollar amount',
	petDeposit decimal COMMENT 'dollar amount',
	propertyWebLink varchar(255),
	comments text COMMENT 'final comment box at the bottom of the bid form',
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	sfMonth varchar(255),
	clientID int,
	
	PRIMARY KEY(id),
	UNIQUE (bidRequestID)
);